### ISSUE TITLE
ESC L impl questions

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#10]
Are you familiar with ESC L command? https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=193

The documentation says that this command switches from Standard mode to page mode, but I don't see this switch in the library.   I think we should have, in order to see the effects of commands that work only in page mode, such as GS $ or ESC W.  Do you have any insight about it?

**Comment by zachzurn** [comment]
I have seen the command but I never did anything around page mode. If you want to implement this I think you would have to add some additional fields to the context and possibly modify some of the render commands if it can't be done with the current set.

**Comment by kewynakshlley** [comment]
@zachzurn Yes, I thought something similar. But I wasn't sure about this. I had in mind that I would just need to add some fields in the context, but I didn't realize that I had to change the render too.

The things that I know so far:

- The command facilitates the transition from Standard mode to Page mode, indicating a fundamental shift in the printer's behavior and capabilities.
- Understanding this is good for defining custom print areas and layouts.
- Used alongside with ESC W to set a print area.
- ESC T is used in page mode to define a start position and a print direction.
- FF command print and return to standard mode in page mode

I had in mind that the ESC L would be a big filter where only a couple of commands would work, and those commands would dictate the way that the render would treat the paper. Do you think that this command should modify something in the render?

**Comment by zachzurn** [comment]
Here is an interesting reference for page mode. Would love to somehow get those sample commands as a binary to use as a test file:

https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=271

**Comment by zachzurn** [comment]
It would be interesting to be able to parse this simple format into proper bytes for writing readable test files:

Lines starting with a '//  are comments. tokens are separated by whitespace. if token is surrounded by quotes, it's a string that gets converted to bytes, otherwise it is a constant (ESC) or a numeric value (203).

```
'// ============================================================================
'//  Print in Page mode
'// ============================================================================

'// Initialize printer
    ESC "@"

'// Select Page mode
    ESC "L"
'// Set horizontal and vertical motion units: Horizontal motion unit = 0.125 mm
'// (1/203 inch), vertical motion unit = 0.125 mm (1/203 inch)
'// The above are values based on the dot density of the TM-T20 printing head,
'// and this script must be changed for each model.
    GS "P" 203 203
```
