### ISSUE TITLE
Question about the form feed (FF) command objective

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#16]
The documentation contains two FF commands, first one only works in page mode, where it prints the data and return to standard mode:

https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=12

The other one just ends a job and will be only executed in standard mode:

https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=385

The FF command present in the thermal library just returns some kind of string. What is the objective of the current implementation? I would like to modify this code to handle its real objective, depending on the mode that the library is currently in, but I am still confusing on how I will tell to the library to print the data and delete it, following what the documentation says:

- This command is enabled only in Page mode. See FF (in Standard mode) to use this command in Standard mode. Page mode can be selected by [ESC L](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=193#esc_cl).
- The data is deleted in the print area after being printed.
- This command returns the values set by [ESC W](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=56#esc_cw) to the default values.
- The value set by [ESC T](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=55#esc_ct) is maintained.
- After printing, the printer returns to Standard mode and moves the print position to left side of the printable area. Also, the printer is in the status "[Beginning of the line](https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=7#glossary.bol)".

Current FF command:

```rust 

impl CommandHandler for Handler {
    fn get_text(&self, _command: &Command, _context: &Context) -> Option<String> {
        Some("\x0c".to_string())
    }
}
```

**Comment by zachzurn** [comment]
We can do this one of two ways:
1. Implement the logic in the renderer when the FF text comes in (I think that is what \x0c is supposed to be)
2. Change this command type to emit a command that ends the job (EndPrint and maybe an EndPageMode command if in page mode.)
