### ISSUE TITLE
ESC T implementation

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#18]
https://www.epson-biz.com/modules/ref_escpos/index.php?content_id=55#esc_ct

I am completely clueless on how to approach this problem. It contains print direction and starting position, two values that aren't mentioned in the library. So I thought about introducing new fields to the Image or ImageRef structs to store the print direction (e.g., u8 for 0=normal, 1=rotated 90°, etc.) and start position (e.g., a pair of u32 values for X and Y coordinates).

![image](https://github.com/zachzurn/thermal/assets/24993749/54d6fe0f-f71d-4422-b52e-120b2b4c94f6)

what do you think?

**Comment by zachzurn** [comment]
We should most likely have a page mode context. Some rough thoughts:

x : current x axis
y: current y axis
w: page mode width
h: page mode height
dir: lr bt rl tb

When the starting position is set, we set the x and y

A: x = 0, y = 0
B: x = 0, y = h  
C: x = w, y = h
D: x = w, y = 0

The renderer would then send pixels when commands are executed (Images would be rotated/flipped based on the direction), with instructions to not advance the standard mode x and y. Not sure exactly how we deal with text here, but may need to add some directionality to text rendering and the ability to prevent moving the standard x and y. Does page mode allow for text?

When page mode ends, we would then advance the standard mode y to page mode height and zero out the standard mode x.

**Comment by zachzurn** [comment]
I'm going to put together a branch for this. ^

**Comment by zachzurn** [comment]
https://github.com/zachzurn/thermal/tree/feat/page_mode super wip, feel free to play around in this.
