### ISSUE TITLE
Existing examples outputs wrong text alignment and doesn't display some logos

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#2]
This library needs a specific OS and Rust version to work? I am able to convert the existing examples to image, but things are a bit weird. Some logos aren't being rendered, and text alignment isn't correct.

code:

```rust Rust
use thermal_parser::command::Command;
use thermal_parser::context::Context;
use thermal_renderer::image_renderer::ImageRenderer;
use thermal_renderer::renderer::CommandRenderer;

fn main() {
    println!("Thermal parsing!");

    let bytes = std::fs::read("/path/test_receipt_2.bin".to_string()).unwrap();

    let mut context = Context::new();

    let mut image_renderer = ImageRenderer::new("./resources".to_string());

    let on_new_command = move |cmd: Command| {
        image_renderer.process_command(&mut context, &cmd);
    };

    let mut command_parser = thermal_parser::new_esc_pos_parser(Box::from(on_new_command));

    command_parser.parse_bytes(&bytes);
}

```

**Comment by zachzurn** [comment]
There shouldn't be any OS differences. What OS and Rust version are you on?

**Comment by kewynakshlley** [comment]
rustc and cargo 1.73.0 (cc66ad468 2023-10-03) with Windows 10 home. 

The code should be rendering this image of your example:

![test_receipt_2](https://github.com/zachzurn/thermal/assets/24993749/6937c868-b2a1-4f37-8c4c-27a51e808616)

But when I execute the code, it renders the image like this:

![28321633_1](https://github.com/zachzurn/thermal/assets/24993749/8d5791d9-da30-470a-9b2e-ae43ae572e67)

**Comment by zachzurn** [comment]
Pushed a fix for the alignment issues. X and Y scale is still not implemented, so the "ExampleMart.." and "Total   $14.75" will not be rendered properly until that feature is completed.

**Comment by kewynakshlley** [comment]
It's working fine now. Thanks a lot @zachzurn for the fast and helpful response.

**Comment by kewynakshlley** [comment]
Do you have any idea about when this feature will be ready? Although this alignment issue is resolved, this library can't render some logos in receipts. By the way, I can open a new issue for that.

**Comment by zachzurn** [comment]
Sure, if you can provide the receipt bin file with the ticket that would be great. I haven't fully finished the project since there hasn't been much interest. I have no timeline for the scaled fonts yet. Contributions are welcome as well.

**Comment by zachzurn** [comment]
@kewynakshlley were you referring to the column image test that is in the repository or a different image?

**Comment by kewynakshlley** [comment]
It's a different image. The barcodes encoded as ITF are not being rendered properly.  I think it's not being able to identify which ESC command to use in some cases. 

![image](https://github.com/zachzurn/thermal/assets/24993749/10031cd7-923e-4a97-9799-261bba9d7257)

Begin Print
Set Text Justification [01]
Unknown Command [1D, 28, 47, 47, 02, 00, 50, 01]

**Comment by zachzurn** [comment]
That command is "GS ( G" which is not a command that I am aware of. For the ITF, can you post the binary commands used for that one, in a separate ticket.  Scaled fonts have been implemented.
