### ISSUE TITLE
Implement Page Mode

### ISSUE THREAD

**Issue by zachzurn** [zachzurn/thermal#21]

**Comment by kewynakshlley** [comment]
I don't have permission to push on feat/page_mode but I found some problems in the ESC W regarding some operations, causing "attempt to subtract with overflow". 

changed it to 

```
let adjusted_width =
                if context.graphics.x as u16 >= horizontal_logical_origin {
                    context.graphics.x as u16 - horizontal_logical_origin
                } else {
                    0
                };

            let adjusted_height =
                if context.graphics.y as u16 >= vertical_logical_origin {
                    context.graphics.y as u16 - vertical_logical_origin
                } else {
                    0
                };
```

Currently, the provided code is just printing some unformatted metadata.

![image](https://github.com/zachzurn/thermal/assets/24993749/c5633ebb-3354-4fcb-a627-eb15a5d17044)

**Comment by zachzurn** [comment]
The branch is completely untested. I haven't figured out how to give you access to a repo yet. In the meantime you can maybe pull it down and create pull requests on it.

**Comment by zachzurn** [comment]
Cool!!!

It looks pretty good so far. If you take the direction and feed it to the thermal image, I think you will have it. You would need to create a property in there called direction that will insert pixels from the x and y in the right direction. (I can also take a stab if you make a pull request to the page mode branch.

**Comment by zachzurn** [comment]
Page mode is hard. I will get to it when I get a chunk of time where I can finish it.

**Comment by zachzurn** [comment]
Page mode is done

**Comment by kewynakshlley** [comment]
That's great newsssss! Thanks a lot for that! It will be really, really useful.

**Comment by zachzurn** [comment]
> That's great newsssss! Thanks a lot for that! It will be really, really useful.

Let me know if you have any issues or want to add any test files to the repo.  Ideally test files are in the .thermal format.
