### ISSUE TITLE
[BUG] Page mode binary not rendered porperly as image

### ISSUE THREAD

**Issue by kewynakshlley** [zachzurn/thermal#27]
**Describe the bug**
When I try to render the page mode I see:

![image](https://github.com/user-attachments/assets/4a805e3f-d0eb-49aa-b4ef-a062ded39ac5)

**To Reproduce**
```
use std::fs::File;
use std::io::{BufWriter, Read};
use std::path::Path;
use png::BitDepth;
use thermal_parser::thermal_file::parse_str;
use thermal_renderer::image_renderer::ImageRenderer;

fn main() {
    // Read string from thermal file and handle the potential error
    /*let mut file = File::open("hello_world.thermal").unwrap();
    let mut text = String::new();
    file.read_to_string(&mut text).unwrap();  // Unwrap to get the string content or handle the error

    // Parse into esc/pos commands (returns Vec<u8>)
    */
    let bytes = std::fs::read("MY ABSOLUTE PATH/projects/thermal/sample_files/in/page_mode.thermal".to_string()).unwrap();

    // Render to image (ImageRenderer::render expects a reference to Vec<u8>)
    let renders = ImageRenderer::render(&bytes);  // Pass reference to bytes

    // renders.output may contain multiple renders
    // For this example, we grab the first render
    if let Some(render) = renders.output.first() {
        save_image(&render.bytes, render.width, render.height, "hello_world.png");
    }
}

// Save the image to a file (Error handling omitted for brevity)
fn save_image(bytes: &Vec<u8>, width: u32, height: u32, out_path: &str) {
    let path = Path::new(out_path);
    let file = File::create(path).unwrap();
    let ref mut writer = BufWriter::new(file);
    let mut encoder = png::Encoder::new(writer, width, height);

    encoder.set_color(png::ColorType::Grayscale);
    encoder.set_depth(BitDepth::Eight);

    let mut writer = encoder.write_header().unwrap();
    writer.write_image_data(bytes).unwrap();
}
```

**Expected behavior**
![image](https://github.com/user-attachments/assets/5dd609ba-2f5d-4eef-a05c-027f86b54e01)

**Additional context**
I haven't tested with HTML yet. But with image this is happening.

**Comment by zachzurn** [comment]
It looks like the raw thermal file format is being passed to the parser. You will first need to parse the thermal file into esc/pos binary:

```
// Read string from thermal file
let text = read_to_string("hello_world.thermal");

//Must parse into esc/pos commands before using the bytes in the parser
let bytes = parse_str( & text);
```

**Comment by kewynakshlley** [comment]
Yep, that's true. Got it !!!

**Comment by zachzurn** [comment]
I would love to have some more tests for Page Mode. If you end up creating some it would be great to include them in the tests.

**Comment by kewynakshlley** [comment]
Yep, I agree. It would be great to have this feature well tested and covered with unit tests. Quick question, have you removed the logs of the parser?

**Comment by zachzurn** [comment]
They were removed from the renderer tests but still remain in the parsing tests. Would you like to still see command logging in the rendering tests?

**Comment by kewynakshlley** [comment]
By following the examples in the README, when rendering images I am not being able to see the logs of the parser as I used to. I think its important to see the logs to check if there is a problem rendering images or html.

**Comment by kewynakshlley** [comment]
@zachzurn what are your thoughts on this? I am not sure, but looks like you're trying to transform this parser to see the commands and buffers in an endpoint, so you removed from the logs. Right? The problem is that right now we don't have anything to see if a problem appeared in the rendering and parsing process.

**Comment by zachzurn** [comment]
I am adding debugging output back into the tests. I agree with the need for that.

I have asl added the ability to decompile bin files into the thermal format, which is a major buff for debugging and testing.

All of this is on the thermal_debug branch. 

I am currently investigating the issues with page mode with the new binary you provided.

Available documentation for the actual runtime is zero which makes it difficult to implement things perfectly without a good set of test files.

**Comment by kewynakshlley** [comment]
Would be good to have it in the main operations: Image and HTML renderer. I have 0 feedbacks when converting bin to those metadatas. Would be good to have it, because if a conversion goes wrong, I would be able to see in a metrics pipeline.
